name: Node.js CI

on:
    pull_request:
        branches: [ main ]
    push:
        branches:
            - main
            - 'feature/*'  # Runs for branches like 'feature/implementing_change_pw'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            
            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                node-version: '18'

            - name: Install dependencies # Install all modules in node_modules
              run: npm install

            - name: Run ESlint
              run: npm run lint
            
            - name: Build application
              run: npm run build